// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Villa7.Infrastructure.Persistence;

#nullable disable

namespace Villa7.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714032715_AddStateAuditFields")]
    partial class AddStateAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Villa7.Domain.Entities.Habitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<int>("CapacidadMax")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_max");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCambioEstado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio_estado");

                    b.Property<string>("ImagenStoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("imagen_storage_path");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("MotivoCambioEstado")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_cambio_estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_por_noche");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ubicacion");

                    b.Property<string>("UsuarioCambioEstado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_cambio_estado");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("habitaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_habitaciones_capacidad_max", "capacidad_max > 0");

                            t.HasCheckConstraint("CK_habitaciones_precio_por_noche", "precio_por_noche > 0");
                        });
                });

            modelBuilder.Entity("Villa7.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCambioEstado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio_estado");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cancelacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrada");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_salida");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("habitacion_id");

                    b.Property<string>("MotivoCambioEstado")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_cambio_estado");

                    b.Property<decimal>("TotalCalculado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_calculado");

                    b.Property<string>("UsuarioCambioEstado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_cambio_estado");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_reservas_estado");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_reservas_usuario_id");

                    b.HasIndex("HabitacionId", "FechaEntrada", "FechaSalida")
                        .HasDatabaseName("IX_reservas_habitacion_fechas")
                        .HasFilter("estado IN ('Pendiente', 'Confirmada')");

                    b.ToTable("reservas", null, t =>
                        {
                            t.HasCheckConstraint("CK_reservas_estado", "estado IN ('Pendiente', 'Confirmada', 'Cancelada', 'Completada', 'Anulada')");

                            t.HasCheckConstraint("CK_reservas_fechas", "fecha_salida > fecha_entrada");

                            t.HasCheckConstraint("CK_reservas_total_calculado", "total_calculado >= 0");
                        });
                });

            modelBuilder.Entity("Villa7.Domain.Entities.ReservaServicio", b =>
                {
                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("servicio_id");

                    b.Property<decimal>("PrecioContratado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_contratado");

                    b.HasKey("ReservaId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("reserva_servicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_reserva_servicios_precio_contratado", "precio_contratado >= 0");
                        });
                });

            modelBuilder.Entity("Villa7.Domain.Entities.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCambioEstado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio_estado");

                    b.Property<string>("MotivoCambioEstado")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_cambio_estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<string>("UsuarioCambioEstado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_cambio_estado");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("servicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_servicios_precio", "precio >= 0");
                        });
                });

            modelBuilder.Entity("Villa7.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaCambioEstado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio_estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("MotivoCambioEstado")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_cambio_estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiracion");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<string>("UsuarioCambioEstado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_cambio_estado");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_usuarios_rol", "rol IN ('Cliente', 'Administrador')");
                        });
                });

            modelBuilder.Entity("Villa7.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Villa7.Domain.Entities.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Villa7.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Villa7.Domain.Entities.ReservaServicio", b =>
                {
                    b.HasOne("Villa7.Domain.Entities.Reserva", "Reserva")
                        .WithMany("ReservaServicios")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Villa7.Domain.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Villa7.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("ReservaServicios");
                });
#pragma warning restore 612, 618
        }
    }
}
